### ISSUE TITLE
(BUG Report) CPU goes crazy hot while trying to play a HDR video on Maple

### ISSUE THREAD

**Issue by kgvarunkanth** [cryptomilk/android_kernel_sony_msm8998#101]
Android version : 10.0.0
Kernel Version  : 4.4.230
Device               : Maple_DSDS
Bug                    : CPU goes more than 80 degree celcius when trying to play a video on HDR mode on youtube....
                             Battery touches 48  degree celcius in few minutes while the video plays..
 How to reproduce : Play a random HDR 60fps video on youtube and run CPU Float app along with it 
                                 You can see CPU and Battery going so hot in few minutes  Thank you :-)

**Comment by derfelot** [comment]
any specific reason that makes you think this is a kernel issue?

**Comment by kgvarunkanth** [comment]
The ROMs that use this kernel seem to have this weird issue 😅
You can check with bliss 12.10 tho :-)

**Comment by derfelot** [comment]
the Roms that use this kernel also use our device tree, just modified for different Roms

**Comment by derfelot** [comment]
in any case, we don't even have a maple to test, that's always a special case. post some logs and we can have a look

**Comment by kgvarunkanth** [comment]
Yes of course
That's y I raised this issue here

**Comment by kgvarunkanth** [comment]
Ok sure gimme some time
Will take logs right now

**Comment by derfelot** [comment]
unless its definitely a kernel issue, I think its better to post issues in yoshino. buy don't worry for this one now

**Comment by kgvarunkanth** [comment]
Ok... Link to yoshino thread?

**Comment by derfelot** [comment]
https://github.com/cryptomilk/android_device_sony_yoshino

**Comment by kgvarunkanth** [comment]
Took log BTW 
Waiting for my device to cool

**Comment by derfelot** [comment]
that's the common repo shared by lilac, maple and poplar

**Comment by kgvarunkanth** [comment]
https://del.dog/ilocrethep.txt

Grabbed logs 
Waited for device to go crazy hot

**Comment by MFShujath** [comment]
> Android version : 10.0.0
> Kernel Version : 4.4.230
> Device : Maple_DSDS
> Bug : CPU goes more than 80 degree celcius when trying to play a video on HDR mode on youtube....
> Battery touches 48 degree celcius in few minutes while the video plays..
> How to reproduce : Play a random HDR 60fps video on youtube and run CPU Float app along with it
> You can see CPU and Battery going so hot in few minutes Thank you :-)

Ok I dont know if this is related, but I had to disable some codecs from Maple dsi to get the maps working.

Where we open the Google Maps screen would go haevier and show pixels and auto reboot and after modifying the codecs it started working fine.

Logs for that crash : 


06-27 19:29:11.901     0     0 I dsi_recheck_clk_state: 642       =>[53025   :144132686  :        1][14601]:1 1 1 1
06-27 19:29:11.901     0     0 I mdss_dsi_clk_req_state: 841      =>[53026   :144132686  :        0][14601]:1 3 1 0 0
06-27 19:29:11.901     0     0 I mdss_dsi_clk_req_state: 907      =>[53027   :144132687  :        1][14601]:1 3 1 1 1
06-27 19:29:11.901     0     0 I dsi_recheck_clk_state: 642       =>[53028   :144132687  :        0][14601]:1 1 1 1
06-27 19:29:11.902     0     0 I mdss_dsi_clk_req_state: 841      =>[53029   :144132697  :       10][14601]:0 3 1 1 1
06-27 19:29:11.902     0     0 I mdss_dsi_clk_req_state: 907      =>[53030   :144132697  :        0][14601]:0 3 1 1 1
06-27 19:29:11.902     0     0 I mdss_dsi_clk_req_state: 841      =>[53031   :144132698  :        1][14601]:1 3 0 1 1
06-27 19:29:11.902     0     0 I mdss_dsi_clk_req_state: 907      =>[53032   :144132698  :        0][14601]:1 3 0 0 0
06-27 19:29:11.902     0     0 I dsi_recheck_clk_state: 642       =>[53033   :144132698  :        0][14601]:1 1 1 1
06-27 19:29:11.902     0     0 I mdss_dsi_clk_req_state: 841      =>[53034   :144132699  :        1][14601]:0 3 0 1 1
06-27 19:29:11.902     0     0 I mdss_dsi_clk_req_state: 907      =>[53035   :144132699  :        0][14601]:0 3 0 1 1
06-27 19:29:11.902     0     0 I mdss_dsi_clk_req_state: 841      =>[53036   :144132699  :        0][14601]:0 3 0 1 1
06-27 19:29:11.902     0     0 I mdss_dsi_clk_req_state: 907      =>[53037   :144132699  :        0][14601]:0 3 0 0 0
06-27 19:29:11.902     0     0 I dsi_recheck_clk_state: 642       =>[53038   :144132700  :        1][14601]:1 1 1 1
06-27 19:29:11.902     0     0 I mdss_mdp_display_commit: 6081    =>[53039   :144132712  :       12][14601]:2 2000 4000 0 1
06-27 19:29:11.902     0     0 I mdss_mdp_cmd_kickoff: 3164       =>[53040   :144132717  :        5][14601]:0 0 0 0 870 f00
06-27 19:29:11.902     0     0 I mdss_mdp_resource_control: 786   =>[53041   :144132719  :        2][14601]:0 1 1 1111
06-27 19:29:11.902     0     0 I mdss_mdp_resource_control: 825   =>[53042   :144132722  :        3][14601]:0 1 1 11
06-27 19:29:11.902     0     0 I mdss_mdp_resource_control: 1094  =>[53043   :144132722  :        0][14601]:1 1 2222
06-27 19:29:11.902     0     0 I mdss_dsi_event_handler: 2981     =>[53044   :144132724  :        2][14601]:11 0 0 3333
06-27 19:29:11.902     0     0 I mdss_dsi_cmdlist_commit: 2777    =>[53045   :144132725  :        1][14601]:0 1 0 3909 1111
06-27 19:29:11.902     0     0 I mdss_dsi_cmd_mdp_busy: 2619      =>[53046   :144132726  :        1][14601]:0 0 3909 1111
06-27 19:29:11.902     0     0 I mdss_dsi_cmd_mdp_busy: 2650      =>[53047   :144132727  :        1][14601]:0 0 3909 2222
06-27 19:29:11.902     0     0 I mdss_dsi_cmdlist_commit: 2909    =>[53048   :144132728  :        1][14601]:0 1 0 3909 2222
06-27 19:29:11.902     0     0 I mdss_dsi_enable_irq: 217         =>[53049   :144132728  :        0][14601]:0 100
06-27 19:29:11.902     0     0 I mdss_dsi_cmd_mdp_start: 2560     =>[53050   :144132730  :        2][14601]:0 1 3909
06-27 19:29:11.902     0     0 I mdss_dsi_event_handler: 2981     =>[53051   :144132730  :        0][14601]:11 0 1 3333
06-27 19:29:11.902     0     0 I mdss_dsi_cmdlist_commit: 2777    =>[53052   :144132731  :        1][14601]:1 1 0 3909 1111
06-27 19:29:11.902     0     0 I mdss_dsi_cmd_mdp_busy: 2619      =>[53053   :144132731  :        0][14601]:1 0 3909 1111
06-27 19:29:11.902     0     0 I mdss_dsi_cmd_mdp_busy: 2650      =>[53054   :144132731  :        0][14601]:1 0 3909 2222
06-27 19:29:11.902     0     0 I mdss_dsi_cmdlist_commit: 2909    =>[53055   :144132732  :        1][14601]:1 1 0 3909 2222
06-27 19:29:11.902     0     0 I mdss_dsi_cmd_mdp_start: 2560     =>[53056   :144132732  :        0][14601]:1 1 3909
06-27 19:29:11.902     0     0 I __mdss_mdp_kickoff: 2990         =>[53057   :144132740  :        8][14601]:0
06-27 19:29:11.902     0     0 I wait_for_read_ptr_if_late: 2972  =>[53058   :144132748  :        8][14601]:140 141 0

**Comment by MFShujath** [comment]
DefaultDisplay: Display size changed from Point(2160, 3840) to Point(1080, 1920)
ConfigMonitor: Display size changed from Point(2160, 3840) to Point(1080, 1920)

**Comment by derfelot** [comment]
Is the HDR prop set on maple?

`ro.surface_flinger.has_HDR_display=true`

if not, does that fix the issue? Also, please open a new issue at https://github.com/whatawurst/android_device_sony_yoshino as this repo will soon disappear. We are moving all our sources there.
